### ISSUE TITLE
issue #2 (March, 2018)

### ISSUE THREAD

**Issue by raidel-dev** [dalba1992/ringsidenews#2]

**Comment by raidel-dev** [comment]
Hi, Aplus.
How are you?
This is our lab's requirement and it is urgent, also.
*************************************************************
△References
Hi3519 V100 Demo Board User Guide.pdf
Hi3519 V100 Professional HDIP Camera SoC Brief DataSheet.pdf
Hi3519 V101 Professional HDIP Camera SoC Brief DataSheet.pdf
Hi3516C V300 Demo Board User Guide.pdf
www.panuso.com/68176056.html
	HiMPP IPC V3.0 Media Processing Software Development Reference.pdf
www.panuso.com/44059644.html
	HiMPP IPC V2.0 Media Processing Software Development Reference.pdf (Hi3516A)
www.panuso.com/68176135.html
	HiMPP IPC V2.0 Media Processing Software Development Reference.pdf (Hi3519)


Z3-C6678-RPS Starter Kit data
Z3-HE1080-RPS Starter Kit data
TMDDM365 data
TMDDM368 data
TMDDM6446 data

 
△Development Kit(Board) price
Hi3516A Demo Board
Hi3516D Demo Board
Hi3516C Demo Board
Hi3519A(Hi3519D, Hi3519C) Demo Board
Z3-HE1080-RPS
Z3-C6678-RPS
TMDDM365
TMDDM368

△Price
Hi3516A, 
Hi3516C, 
Hi3516D
Hi3519A, 
Hi3519C, 
Hi3519D
TMS320C6678
TMS320DM6446
TMS320DM365
TMS320DM368

**********************************************************

I want you to upload them to github, for they are security data..
Thanks and regards.

**Comment by raidel-dev** [comment]
There is no demo board for these products.

Hi3516A : US $102.35 - 131.10 / piece
Hi3516D : US $41.08 / piece
Hi3516C : US $22.80 / piece
Hi3519A : US $50-185  / Piece
Hi3519D : US $24.0-30.0  / Piece
Hi3519C : US $24.0-30.0  / Piece
Z3-HE1080-RPS : No such product
Z3-C6678-RPS : No such product
TMDDM365 : No such product
TMDDM368 : No such product

[Hi3519.pdf](https://github.com/dalba1992/ringsidenews/files/1754161/Hi3519.pdf)
[tms320dm6446.pdf](https://github.com/dalba1992/ringsidenews/files/1754166/tms320dm6446.pdf)

Uploading these two files took 30 minutes. Please use Mega with password.
Rest of all PDFs are not existing or should be paid.
Your written URLs are fake.

Hello, Minh and Liuwei.
How are you all? going well?
Take care of your health first.

**Comment by raidel-dev** [comment]
I can't download Hi3519.pdf and tms320dm6446.pdf.

**Comment by raidel-dev** [comment]
I want you to upload the pdfs as uploading source code to github.
You will be able to split the data with small compressed size.
It's okay even if it takes a few days.
Thanks in advance.
BR.

**Comment by raidel-dev** [comment]
I uploaded to lab6-data repository
it was failed during working days because of high traffic.
So I succeeded even on today.

**Comment by raidel-dev** [comment]
Thanks.

**Comment by raidel-dev** [comment]
Hi, Aplus.
How are you and how's everything?
There was an error in signing in github.
https://ibug.doc.ic.ac.uk/media/uploads/documents/deng_marginal_loss_for_cvpr_2017_paper.pdf
https://ydwen.github.io/papers/WenECCV16.pdf
These are request of our boss.
Hope hearing from you soon.
Regards.

**Comment by raidel-dev** [comment]
Hello.
Hope you are well
I pushed to lab6-data
Thanks.

**Comment by raidel-dev** [comment]
Hi, Aplus.
You will be forever with our lab :)
This is a book name "Learning with kernels: Support vector machines, regularization, optimization, and beyond".
Hope sending it asap.
Wish your good health.
Minh.

**Comment by raidel-dev** [comment]
It should be paid for reading or download.
So I upload similar one.
There is no other similar one.

**Comment by dalba1992** [comment]
https://cds.cern.ch/record/791819/files/0262194759_TOC.pdf
What about this url?

**Comment by dalba1992** [comment]
Hello, A+.
How are you?
How's it going?
I hope you are well.
Here are some requests from the boss.
These data are from samsung board.
- S5P4412 HW Multimedia Codec(MFC) User's Guide
   document and sample code.
- API Document S5P4412 Multi-Format Codec
   document and sample code
- S5P4412_Linux x.x_MFC_API_REV
   document and sample code
- FIMV_MFC_V x.x (S5P4412)
   document and sample code.
- HM x.x (regarding HEVC)
HEVC engine code with higher version

Liu said that you could upload big data easily on github if you use desktop app.

Thanks and regards.

Minh.

**Comment by dalba1992** [comment]
Hello, A+.
How are you?
How's it going?
I hope you are well.
Here are some requests from the boss.
These data are from samsung board.
- S5P4412 HW Multimedia Codec(MFC) User's Guide
   document and sample code.
- API Document S5P4412 Multi-Format Codec
   document and sample code
- S5P4412_Linux x.x_MFC_API_REV
   document and sample code
- FIMV_MFC_V x.x (S5P4412)
   document and sample code.
- HM x.x (regarding HEVC)
HEVC engine code with higher version

Liu said that you could upload big data easily on github if you use desktop app.

Thanks and regards.

Minh.

**Comment by raidel-dev** [comment]
Hello, A+.
How are you?
How's it going?
I hope you are well.
Here are some requests from the boss.
These data are from samsung board.
- S5P4412 HW Multimedia Codec(MFC) User's Guide
   document and sample code.
- API Document S5P4412 Multi-Format Codec
   document and sample code
- S5P4412_Linux x.x_MFC_API_REV
   document and sample code
- FIMV_MFC_V x.x (S5P4412)
   document and sample code.
- HM x.x (regarding HEVC)
HEVC engine code with higher version

Liu said that you could upload big data easily on github if you use desktop app.

Thanks and regards.

Minh.

**Comment by raidel-dev** [comment]
Hello, everyone. Hope you all are very well. 
Here there was a big check from outside so here's all PC was formatted.
https://github.com/bciar/lab6
Please download here.

Unfortunately there is no data for these information.
S5P4412_Linux x.x_MFC_API_REV
FIMV_MFC_V x.x (S5P4412)
Thanks
